version: '3.5'

services:

  rapter-test:
    container_name: rapter-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      

